name: assignment_task_app
description: Assignment Task App - Flutter + GetX skeleton
publish_to: 'none'
version: 0.0.1

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  get: ^4.7.2
  http: ^0.13.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  visibility_detector: ^0.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.4.0
  hive_generator: ^2.0.0

flutter:
  uses-material-design: true
